### ISSUE TITLE
Add some build instructions.

### ISSUE THREAD

**Issue by crawley** [Pablo87996/Zoo_Game#1]
A project on Github needs some build instructions in the README file.  (Or a Gradle / Maven / Ant or whatever build file to automate the process.)

Otherwise we get Java newbies asking questions like [this](https://stackoverflow.com/questions/77569332) on StackOverflow.

**Comment by efw234** [comment]
I tried building your project but there are alot of issues.. Someone told me you could have built it wrongly. Maybe you can add a more detailed readme with screenshots and steps for others to know how to set up? I am using Eclispe IDE

**Comment by Pablo87996** [comment]
Hello, everyone. Thank you for your advises. I made this project in the Visual Studio Code, and to execute I've been using the Java's version 8 Update 381 and these extensions:
* Extension Pack for Java;
* Debugger for Java;
* Test Runner for Java;
* Maven for Java;
* Project Manager for Java; and
* Language Support for Java(TM) by Red Hat.

Otherwise, I tried import this project to NetBeans, but it didn't work, because it's able to import only projects made in this program. To conclude, I'll try resolve this issue, but for while, I suggest you try import the project in the VS Code with these extensions.

**Comment by Pablo87996** [comment]
Hello, again. I downloaded the Eclipse IDE and when I run the project I have the same error. So, I did some searches and I discovered that you need add the JPlay library to the Java Build Path and change the order in the list.

## Step 1 - Add libraries to Build Path
On the folder **lib**, click with the right button in the jar files and go to the option **Build Path**; after that, click in **Add to Build Path** (I've already done it).
![image](https://github.com/Pablo87996/Zoo_Game/assets/89580852/f265304f-afc9-43c7-8783-bdbcfff8cf9f)

## Step 2 - Configure Build Path
Click with the right button in one of the jar files again, go to the option **Build Path** and click in **Configure Build Path**. In addition, mark the checkboxes and put the JPlay files on the top, clicking them and in the button Top.
![image](https://github.com/Pablo87996/Zoo_Game/assets/89580852/c81f742c-a413-4a8d-8dbd-93380c4adc31)

I will do a commit with this configuration, try download again or follow these steps.
Thank you again for contact me, @crawley and @efw234. Furthermore, I am awaiting your responses.

**Comment by efw234** [comment]
@Pablo87996 Thanks for the response. I have tried importing your project on my Eclispe IDE and I can run it now. Looking forward to seeing more features added!

**Comment by Pablo87996** [comment]
My pleasure! Please, starring the repository to support me 😃⭐.

**Comment by Pablo87996** [comment]
I'm closing this issue, because the problem was resolved and I added the build instructions on README.
